final check = {
  "success": true,
  "message": "Team fetched successfully",
  "data": {
    "id": "a3963715-ef72-46f6-a5e2-42cb530efb17",
    "teamId": "teamA-574732",
    "name": "Test Team A",
    "logo": "logoA.png",
    "banner": "bannerA.png",
    "location": {"area": "Sector 18", "city": "Noida", "state": "UP"},
    "players": [
      {
        "id": "eb6bbfb8-14d0-4689-9587-0230157abd24",
        "playerId": "user2-61057",
        "name": "User 2",
        "profilePhoto": null,
        "playerRole": "Active_Squad",
        "playerType": "AllRounder",
        "batsmanType": "RIGHT_HANDED",
        "bowlerType": "RIGHT_ARM_FAST",
      },
      {
        "id": "af591c63-0465-4aaf-a840-4ec4327cc4d0",
        "playerId": "user5-552972",
        "name": "User 5",
        "profilePhoto": null,
        "playerRole": "Active_Squad",
        "playerType": "AllRounder",
        "batsmanType": "RIGHT_HANDED",
        "bowlerType": "RIGHT_ARM_FAST",
      },
      {
        "id": "eb3ec1a1-7285-4ae7-8fd3-e435fa5ed7fc",
        "playerId": "user3-771397",
        "name": "User 3",
        "profilePhoto": null,
        "playerRole": "Active_Squad",
        "playerType": "AllRounder",
        "batsmanType": "RIGHT_HANDED",
        "bowlerType": "RIGHT_ARM_FAST",
      },
      {
        "id": "c94e8bd4-4b58-43be-a62c-0a2a9d20b145",
        "playerId": "user1-704563",
        "name": "User 1",
        "profilePhoto": null,
        "playerRole": "Captain",
        "playerType": "AllRounder",
        "batsmanType": "RIGHT_HANDED",
        "bowlerType": "RIGHT_ARM_FAST",
      },
      {
        "id": "1026f632-2975-42b6-a33b-ad2b9b6ad25a",
        "playerId": "user4-975962",
        "name": "User 4",
        "profilePhoto": null,
        "playerRole": "Active_Squad",
        "playerType": "AllRounder",
        "batsmanType": "RIGHT_HANDED",
        "bowlerType": "RIGHT_ARM_FAST",
      },
    ],
    "teamStats": {
      "matches": 19,
      "wins": 9,
      "losses": 10,
      "draws": 0,
      "abandoned": 0,
      "nrr": 0,
      "tossWins": 10,
      "batFirst": 0,
      "batFirstWins": 0,
      "batFirstLoss": 0,
      "bowlFirst": 19,
      "bowlFirstWins": 9,
      "bowlFirstLoss": 10,
      "highestRunsScored": 20,
      "lowestRunsScored": 20,
      "highestRunsConceded": 37,
      "lowestRunsConceded": 37,
    },
    "followersCount": 1,
    "followingCount": 0,
    "follows": true,
    "playerStats": {
      "batting": [
        {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "runs": 181,
          "balls": 0,
          "fours": 0,
          "sixes": 0,
          "hundreds": 0,
          "fifties": 0,
          "thirties": 0,
          "ducks": 0,
          "average": 0,
          "strikeRate": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 139,
          "balls": 0,
          "fours": 0,
          "sixes": 0,
          "hundreds": 0,
          "fifties": 0,
          "thirties": 0,
          "ducks": 0,
          "average": 0,
          "strikeRate": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 90,
          "balls": 0,
          "fours": 0,
          "sixes": 0,
          "hundreds": 0,
          "fifties": 0,
          "thirties": 0,
          "ducks": 0,
          "average": 0,
          "strikeRate": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "runs": 88,
          "balls": 0,
          "fours": 0,
          "sixes": 0,
          "hundreds": 0,
          "fifties": 0,
          "thirties": 0,
          "ducks": 0,
          "average": 0,
          "strikeRate": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 44,
          "balls": 0,
          "fours": 0,
          "sixes": 0,
          "hundreds": 0,
          "fifties": 0,
          "thirties": 0,
          "ducks": 0,
          "average": 0,
          "strikeRate": 0,
          "matches": 20,
        },
      ],
      "bowling": [
        {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "wickets": 14,
          "runs": 0,
          "overs": 0,
          "maidens": 0,
          "dots": 0,
          "average": 0,
          "economy": 0,
          "strikeRate": 0,
          "threeWickets": 0,
          "fiveWickets": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "wickets": 14,
          "runs": 0,
          "overs": 0,
          "maidens": 0,
          "dots": 0,
          "average": 0,
          "economy": 0,
          "strikeRate": 0,
          "threeWickets": 0,
          "fiveWickets": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "wickets": 2,
          "runs": 0,
          "overs": 0,
          "maidens": 0,
          "dots": 0,
          "average": 0,
          "economy": 0,
          "strikeRate": 0,
          "threeWickets": 0,
          "fiveWickets": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "wickets": 2,
          "runs": 0,
          "overs": 0,
          "maidens": 0,
          "dots": 0,
          "average": 0,
          "economy": 0,
          "strikeRate": 0,
          "threeWickets": 0,
          "fiveWickets": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "wickets": 0,
          "runs": 0,
          "overs": 0,
          "maidens": 0,
          "dots": 0,
          "average": 0,
          "economy": 0,
          "strikeRate": 0,
          "threeWickets": 0,
          "fiveWickets": 0,
          "matches": 20,
        },
      ],
      "fielding": [
        {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "catches": 0,
          "stumpings": 0,
          "runouts": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "catches": 0,
          "stumpings": 0,
          "runouts": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "catches": 0,
          "stumpings": 0,
          "runouts": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "catches": 0,
          "stumpings": 0,
          "runouts": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "catches": 0,
          "stumpings": 0,
          "runouts": 0,
          "matches": 20,
        },
      ],
      "partnerships": [
        {
          "partnershipId": "06fc53b3-06f0-4d35-9ce0-d50df9eca8fc",
          "totalRuns": 37,
          "totalBalls": 10,
          "batsman1": {
            "player": {
              "profileId": "user2-61057",
              "name": "User 2",
              "photo": null,
            },
            "runs": 26,
            "balls": 7,
          },
          "batsman2": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 11,
            "balls": 3,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-3",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "2524f5da-cece-4f48-a4c6-1a1201ada2e9",
          "totalRuns": 25,
          "totalBalls": 5,
          "batsman1": {
            "player": {
              "profileId": "user4-975962",
              "name": "User 4",
              "photo": null,
            },
            "runs": 15,
            "balls": 3,
          },
          "batsman2": {
            "player": {
              "profileId": "user1-704563",
              "name": "User 1",
              "photo": null,
            },
            "runs": 10,
            "balls": 2,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-7",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "6552b97f-089c-4230-997b-d1f428db11d9",
          "totalRuns": 24,
          "totalBalls": 7,
          "batsman1": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 5,
            "balls": 2,
          },
          "batsman2": {
            "player": {
              "profileId": "user1-704563",
              "name": "User 1",
              "photo": null,
            },
            "runs": 19,
            "balls": 5,
          },
          "match": {
            "matchId":
                "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-playoff-qualifier1",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "51a18747-777a-49c0-9a92-a1350cce56c6",
          "totalRuns": 24,
          "totalBalls": 6,
          "batsman1": {
            "player": {
              "profileId": "user2-61057",
              "name": "User 2",
              "photo": null,
            },
            "runs": 24,
            "balls": 6,
          },
          "batsman2": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 0,
            "balls": 1,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
            "date": "2025-10-29T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "7bca50be-50e9-40d2-936a-ff1cc8a13226",
          "totalRuns": 14,
          "totalBalls": 4,
          "batsman1": {
            "player": {
              "profileId": "user3-771397",
              "name": "User 3",
              "photo": null,
            },
            "runs": 3,
            "balls": 1,
          },
          "batsman2": {
            "player": {
              "profileId": "user4-975962",
              "name": "User 4",
              "photo": null,
            },
            "runs": 14,
            "balls": 4,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
            "date": "2025-10-29T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "45454698-c045-4eb2-8b6b-46e104356ed5",
          "totalRuns": 12,
          "totalBalls": 5,
          "batsman1": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 12,
            "balls": 6,
          },
          "batsman2": {
            "player": {
              "profileId": "user3-771397",
              "name": "User 3",
              "photo": null,
            },
            "runs": 6,
            "balls": 1,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-10",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "e3e8882b-0cb1-4ffc-89be-860a1cdba0ff",
          "totalRuns": 11,
          "totalBalls": 6,
          "batsman1": {
            "player": {
              "profileId": "user1-704563",
              "name": "User 1",
              "photo": null,
            },
            "runs": 10,
            "balls": 5,
          },
          "batsman2": {
            "player": {
              "profileId": "user2-61057",
              "name": "User 2",
              "photo": null,
            },
            "runs": 1,
            "balls": 2,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-13",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "7b6ef530-2142-477d-a56b-448d55360729",
          "totalRuns": 10,
          "totalBalls": 2,
          "batsman1": {
            "player": {
              "profileId": "user3-771397",
              "name": "User 3",
              "photo": null,
            },
            "runs": 6,
            "balls": 1,
          },
          "batsman2": {
            "player": {
              "profileId": "user4-975962",
              "name": "User 4",
              "photo": null,
            },
            "runs": 4,
            "balls": 1,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-10",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "12efeb81-4bfd-49f1-8473-f628b07924ca",
          "totalRuns": 4,
          "totalBalls": 1,
          "batsman1": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 5,
            "balls": 2,
          },
          "batsman2": {
            "player": {
              "profileId": "user2-61057",
              "name": "User 2",
              "photo": null,
            },
            "runs": 4,
            "balls": 1,
          },
          "match": {
            "matchId":
                "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-playoff-qualifier1",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "8f7e8135-185f-4da7-a1a3-df2ddc35ba01",
          "totalRuns": 3,
          "totalBalls": 2,
          "batsman1": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 0,
            "balls": 1,
          },
          "batsman2": {
            "player": {
              "profileId": "user3-771397",
              "name": "User 3",
              "photo": null,
            },
            "runs": 3,
            "balls": 1,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
            "date": "2025-10-29T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "e826a273-47a6-4d43-94e8-838d7ae9f341",
          "totalRuns": 0,
          "totalBalls": 1,
          "batsman1": {
            "player": {
              "profileId": "user3-771397",
              "name": "User 3",
              "photo": null,
            },
            "runs": 3,
            "balls": 1,
          },
          "batsman2": {
            "player": {
              "profileId": "user1-704563",
              "name": "User 1",
              "photo": null,
            },
            "runs": 0,
            "balls": 1,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
            "date": "2025-10-29T00:00:00.000Z",
          },
        },
        {
          "partnershipId": "e2897598-ef2b-4066-88df-17a1fc367a87",
          "totalRuns": 0,
          "totalBalls": 0,
          "batsman1": {
            "player": {
              "profileId": "user1-704563",
              "name": "User 1",
              "photo": null,
            },
            "runs": 10,
            "balls": 5,
          },
          "batsman2": {
            "player": {
              "profileId": "user5-552972",
              "name": "User 5",
              "photo": null,
            },
            "runs": 0,
            "balls": 0,
          },
          "match": {
            "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-13",
            "date": "2025-10-30T00:00:00.000Z",
          },
        },
      ],
      "points": [
        {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "mvpPoints": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "mvpPoints": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "mvpPoints": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "mvpPoints": 0,
          "matches": 20,
        },
        {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "mvpPoints": 0,
          "matches": 20,
        },
      ],
    },
    "matches": [
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-playoff-qualifier1",
        "date": "2025-10-30T00:00:00.000Z",
        "time": "1970-01-01T20:10:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "QUALIFIER1",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "team-f-669de093-1b5",
          "name": "Mumbai Fighters",
          "logo": "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
        },
        "teamBEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": null,
        "groupName": null,
        "tossWinner": "team-f-669de093-1b5",
        "tossChoice": "bowling",
        "winner": "teamA-574732",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-10",
        "date": "2025-10-30T00:00:00.000Z",
        "time": "1970-01-01T17:35:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "team-e-19df90e5-8f2",
          "name": "Kolkata Eagles",
          "logo": "https://via.placeholder.com/200/8E44AD/FFFFFF?text=E",
        },
        "teamBEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": "55811d7f-677a-41c0-acbd-6d212dc3a2d3",
        "groupName": "League Group",
        "tossWinner": "team-e-19df90e5-8f2",
        "tossChoice": "bowling",
        "winner": "teamA-574732",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-3",
        "date": "2025-10-30T00:00:00.000Z",
        "time": "1970-01-01T16:20:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "team-d-b0fb4a18-46a",
          "name": "Delhi Daredevils",
          "logo": "https://via.placeholder.com/200/004E89/FFFFFF?text=D",
        },
        "teamBEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": "55811d7f-677a-41c0-acbd-6d212dc3a2d3",
        "groupName": "League Group",
        "tossWinner": "team-d-b0fb4a18-46a",
        "tossChoice": "bowling",
        "winner": "teamA-574732",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-7",
        "date": "2025-10-30T00:00:00.000Z",
        "time": "1970-01-01T17:30:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "teamBEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": "55811d7f-677a-41c0-acbd-6d212dc3a2d3",
        "groupName": "League Group",
        "tossWinner": "teamA-574732",
        "tossChoice": "bowling",
        "winner": "teamA-574732",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-13",
        "date": "2025-10-30T00:00:00.000Z",
        "time": "1970-01-01T18:20:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "team-f-669de093-1b5",
          "name": "Mumbai Fighters",
          "logo": "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": "55811d7f-677a-41c0-acbd-6d212dc3a2d3",
        "groupName": "League Group",
        "tossWinner": "teamA-574732",
        "tossChoice": "batting",
        "winner": "teamA-574732",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-PJAwKM3G4Fv",
        "date": "2025-10-29T00:00:00.000Z",
        "time": "1970-01-01T00:55:00.000Z",
        "format": "TEST",
        "overs": 0,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Churchgate",
          "city": "UP",
          "state": "India",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": "teamA-574732",
        "tossChoice": "bowling",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
        "date": "2025-10-29T00:00:00.000Z",
        "time": "1970-01-01T02:15:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "TENNIS",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "team-c-50973b60-4a3",
          "name": "Chennai Champions",
          "logo": "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-PCL-Gm6n2Rqn",
          "name": "Punjab Chargers League",
        },
        "groupId": "55811d7f-677a-41c0-acbd-6d212dc3a2d3",
        "groupName": "League Group",
        "tossWinner": "teamA-574732",
        "tossChoice": "batting",
        "winner": "team-c-50973b60-4a3",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "3a15173d-MG5JKM4ANT2",
        "date": "2025-10-28T00:00:00.000Z",
        "time": "1970-01-01T23:04:00.000Z",
        "format": "TEST",
        "overs": 0,
        "ballType": "LEATHER",
        "matchCategory": "GROUP",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "team-c-50973b60-4a3",
          "name": "Chennai Champions",
          "logo": "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": {
          "tournamentId": "tour-GW-Gm6n2Rqn",
          "name": "Gujarat Warriors",
        },
        "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "tossWinner": "teamA-574732",
        "tossChoice": "batting",
        "winner": "team-c-50973b60-4a3",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-XzAmjY5VR",
        "date": "2025-10-27T00:00:00.000Z",
        "time": "1970-01-01T23:54:00.000Z",
        "format": "TEST",
        "overs": 0,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "batting",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-r8PpQeRDJ",
        "date": "2025-10-27T00:00:00.000Z",
        "time": "1970-01-01T00:20:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "batting",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-w2gYZ8zaa",
        "date": "2025-10-27T00:00:00.000Z",
        "time": "1970-01-01T00:22:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Dawdwad",
          "city": "dawdwa",
          "state": "dawdwa",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "batting",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-PJAY3KV9J",
        "date": "2025-10-26T00:00:00.000Z",
        "time": "1970-01-01T00:30:00.000Z",
        "format": "TEST",
        "overs": 0,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "batting",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-jr1LPQvQD",
        "date": "2025-10-25T00:00:00.000Z",
        "time": "1970-01-01T23:50:00.000Z",
        "format": "TEST",
        "overs": 0,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Area",
          "city": "City",
          "state": "State",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "bowling",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-e3JedAzQJ",
        "date": "2025-10-23T00:00:00.000Z",
        "time": "1970-01-01T11:52:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Dwada",
          "city": "dwada",
          "state": "adad",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": "teamA-574732",
        "tossChoice": "bowling",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-5vkmV3Q1K",
        "date": "2025-10-22T00:00:00.000Z",
        "time": "1970-01-01T15:33:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Completed",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Sggs",
          "city": "hdjsj",
          "state": "jsjks",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": "teamA-574732",
        "tossChoice": "batting",
        "winner": "teamB-642392",
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "a3963715-Nvk3aoAYa",
        "date": "2025-10-21T00:00:00.000Z",
        "time": "1970-01-01T16:20:00.000Z",
        "format": "T10",
        "overs": 10,
        "ballType": "Hard",
        "matchCategory": "OPEN",
        "status": "Ongoing",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Area",
          "city": "city",
          "state": "state",
          "coordinates": null,
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": "bowling",
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
      {
        "matchId": "match-136478",
        "date": "2025-10-21T00:00:00.000Z",
        "time": "1970-01-01T13:34:38.000Z",
        "format": "T20",
        "overs": 5,
        "ballType": "Leather",
        "matchCategory": "OPEN",
        "status": "Upcoming",
        "teamAEntity": {
          "teamId": "teamA-574732",
          "name": "Test Team A",
          "logo": "logoA.png",
        },
        "teamBEntity": {
          "teamId": "teamB-642392",
          "name": "Test Team B",
          "logo": "logoB.png",
        },
        "location": {
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
        "scorerEntity": {
          "profileId": "user1-704563",
          "name": "User 1",
          "profilePhoto": null,
        },
        "tournament": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "draw": false,
        "abandoned": false,
        "targetChanged": false,
      },
    ],
    "tournaments": [
      {
        "tournamentId": "tour-GW-Gm6n2Rqn",
        "tournamentName": "Gujarat Warriors",
        "banner":
            "https://bxgiwtigvagzyllsmxif.supabase.co/storage/v1/object/public/cricklo-user-assets/tournaments/Gujarat%20Warriors/banner.octet-stream",
        "format": "TEST",
        "tournamentType": "KNOCKOUT",
        "overs": 0,
        "ballType": "LEATHER",
        "startDate": "2025-10-29T00:00:00.000Z",
        "endDate": "2025-10-31T00:00:00.000Z",
        "inviteDeadline": "2025-10-29T00:00:00.000Z",
        "numberOfTeams": 12,
        "status": "GROUP_STAGE",
        "createdAt": "2025-10-27T18:39:04.000Z",
        "organizer": {"profileId": "user1-704563", "name": "User 1"},
        "venues": [
          {
            "area": "Area",
            "city": "City",
            "state": "State",
            "coordinates": null,
          },
        ],
      },
      {
        "tournamentId": "tour-PCL-Gm6n2Rqn",
        "tournamentName": "Punjab Chargers League",
        "banner":
            "https://bxgiwtigvagzyllsmxif.supabase.co/storage/v1/object/public/cricklo-user-assets/tournaments/Punjab%20Chargers%20League/banner.octet-stream",
        "format": "T10",
        "tournamentType": "LEAGUE",
        "overs": 10,
        "ballType": "TENNIS",
        "startDate": "2025-10-28T00:00:00.000Z",
        "endDate": "2025-10-31T00:00:00.000Z",
        "inviteDeadline": "2025-10-28T00:00:00.000Z",
        "numberOfTeams": 12,
        "status": "PLAYOFFS",
        "createdAt": "2025-10-27T07:28:26.000Z",
        "organizer": {"profileId": "user1-704563", "name": "User 1"},
        "venues": [
          {
            "area": "Area",
            "city": "City",
            "state": "State",
            "coordinates": null,
          },
        ],
      },
    ],
    "partnerships": [
      {
        "partnershipId": "06fc53b3-06f0-4d35-9ce0-d50df9eca8fc",
        "totalRuns": 37,
        "totalBalls": 10,
        "batsman1": {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "runs": 26,
          "balls": 7,
        },
        "batsman2": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 11,
          "balls": 3,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-3",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "2524f5da-cece-4f48-a4c6-1a1201ada2e9",
        "totalRuns": 25,
        "totalBalls": 5,
        "batsman1": {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "runs": 15,
          "balls": 3,
        },
        "batsman2": {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 10,
          "balls": 2,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-7",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "6552b97f-089c-4230-997b-d1f428db11d9",
        "totalRuns": 24,
        "totalBalls": 7,
        "batsman1": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 5,
          "balls": 2,
        },
        "batsman2": {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 19,
          "balls": 5,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-playoff-qualifier1",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "51a18747-777a-49c0-9a92-a1350cce56c6",
        "totalRuns": 24,
        "totalBalls": 6,
        "batsman1": {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "runs": 24,
          "balls": 6,
        },
        "batsman2": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 0,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
          "date": "2025-10-29T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "7bca50be-50e9-40d2-936a-ff1cc8a13226",
        "totalRuns": 14,
        "totalBalls": 4,
        "batsman1": {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 3,
          "balls": 1,
        },
        "batsman2": {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "runs": 14,
          "balls": 4,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
          "date": "2025-10-29T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "45454698-c045-4eb2-8b6b-46e104356ed5",
        "totalRuns": 12,
        "totalBalls": 5,
        "batsman1": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 12,
          "balls": 6,
        },
        "batsman2": {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 6,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-10",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "e3e8882b-0cb1-4ffc-89be-860a1cdba0ff",
        "totalRuns": 11,
        "totalBalls": 6,
        "batsman1": {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 10,
          "balls": 5,
        },
        "batsman2": {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "runs": 1,
          "balls": 2,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-13",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "7b6ef530-2142-477d-a56b-448d55360729",
        "totalRuns": 10,
        "totalBalls": 2,
        "batsman1": {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 6,
          "balls": 1,
        },
        "batsman2": {
          "player": {
            "profileId": "user4-975962",
            "name": "User 4",
            "photo": null,
          },
          "runs": 4,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-10",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "12efeb81-4bfd-49f1-8473-f628b07924ca",
        "totalRuns": 4,
        "totalBalls": 1,
        "batsman1": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 5,
          "balls": 2,
        },
        "batsman2": {
          "player": {
            "profileId": "user2-61057",
            "name": "User 2",
            "photo": null,
          },
          "runs": 4,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-playoff-qualifier1",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "8f7e8135-185f-4da7-a1a3-df2ddc35ba01",
        "totalRuns": 3,
        "totalBalls": 2,
        "batsman1": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 0,
          "balls": 1,
        },
        "batsman2": {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 3,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
          "date": "2025-10-29T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "e826a273-47a6-4d43-94e8-838d7ae9f341",
        "totalRuns": 0,
        "totalBalls": 1,
        "batsman1": {
          "player": {
            "profileId": "user3-771397",
            "name": "User 3",
            "photo": null,
          },
          "runs": 3,
          "balls": 1,
        },
        "batsman2": {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 0,
          "balls": 1,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-14",
          "date": "2025-10-29T00:00:00.000Z",
        },
      },
      {
        "partnershipId": "e2897598-ef2b-4066-88df-17a1fc367a87",
        "totalRuns": 0,
        "totalBalls": 0,
        "batsman1": {
          "player": {
            "profileId": "user1-704563",
            "name": "User 1",
            "photo": null,
          },
          "runs": 10,
          "balls": 5,
        },
        "batsman2": {
          "player": {
            "profileId": "user5-552972",
            "name": "User 5",
            "photo": null,
          },
          "runs": 0,
          "balls": 0,
        },
        "match": {
          "matchId": "66fe017b-e6dc-4e9c-854c-b2f22c2f7005-group-13",
          "date": "2025-10-30T00:00:00.000Z",
        },
      },
    ],
  },
};
