import 'package:cricklo/core/utils/constants/enums.dart';
import 'package:cricklo/features/login/domain/entities/location_entity.dart';
import 'package:cricklo/features/login/domain/entities/user_entitiy.dart';
import 'package:cricklo/features/teams/domain/entities/player_entity.dart';
import 'package:cricklo/features/teams/domain/entities/team_entity.dart';

final dummyCurrUser = UserEntity(
  phoneNumber: "6386291080",
  name: "Raghvedra Mishra",
  email: "raghvendramishra2002@gmail.com",
  location: LocationEntity(
    area: "Gomti Nagar",
    city: "Lucknow",
    state: "UP",
    lat: 0,
    lng: 0,
  ),
  playerType: PlayerType.allRounder,
  batterType: BatterType.leftHand,
  bowlerType: BowlerType.leftArmPace,
);

final TeamEntity dummyTeam = TeamEntity(
  id: "",
  name: "Hello World",
  teamLogo: "",
  teamBanner: "",
  players: dummyPlayers.getRange(2, 5).toList(),
  location: LocationEntity(
    area: "Lakhimpur",
    city: "Lakhimpur",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
);

final List<PlayerEntity> dummyPlayers = [
  PlayerEntity(
    id: '1',
    teamRole: TeamRole.invited,
    playerId: 'P001',
    name: 'Rohit Sharma',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '2',
    playerId: 'P002',
    name: 'Shikhar Dhawan',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.leftHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.captain,
    id: '3',
    playerId: 'P003',
    name: 'Virat Kohli',
    captain: true,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.member,
    id: '4',
    playerId: 'P004',
    name: 'KL Rahul',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '5',
    playerId: 'P005',
    name: 'Rishabh Pant',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.leftHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '6',
    playerId: 'P006',
    name: 'Hardik Pandya',
    captain: false,
    playerType: PlayerType.allRounder,
    batterType: BatterType.rightHand,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '7',
    playerId: 'P007',
    name: 'Ravindra Jadeja',
    captain: false,
    playerType: PlayerType.allRounder,
    batterType: BatterType.leftHand,
    bowlerType: BowlerType.leftArmSpin,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '8',
    playerId: 'P008',
    name: 'Axar Patel',
    captain: false,
    playerType: PlayerType.allRounder,
    batterType: BatterType.leftHand,
    bowlerType: BowlerType.leftArmSpin,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '9',
    playerId: 'P009',
    name: 'Shreyas Iyer',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '10',
    playerId: 'P010',
    name: 'Suryakumar Yadav',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '11',
    playerId: 'P011',
    name: 'Jasprit Bumrah',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '12',
    playerId: 'P012',
    name: 'Mohammed Shami',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '13',
    playerId: 'P013',
    name: 'Bhuvneshwar Kumar',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '14',
    playerId: 'P014',
    name: 'Yuzvendra Chahal',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmSpin,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '15',
    playerId: 'P015',
    name: 'Kuldeep Yadav',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.leftArmSpin,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '16',
    playerId: 'P016',
    name: 'Washington Sundar',
    captain: false,
    playerType: PlayerType.allRounder,
    batterType: BatterType.leftHand,
    bowlerType: BowlerType.rightArmSpin,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '17',
    playerId: 'P017',
    name: 'Deepak Chahar',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '18',
    playerId: 'P018',
    name: 'Prithvi Shaw',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '19',
    playerId: 'P019',
    name: 'Mayank Agarwal',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    teamRole: TeamRole.invited,
    id: '20',
    playerId: 'P020',
    name: 'Sanju Samson',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
];
