import 'package:cricklo/core/utils/constants/enums.dart';
import 'package:cricklo/features/login/domain/entities/location_entity.dart';
import 'package:cricklo/features/login/domain/entities/user_entitiy.dart';
import 'package:cricklo/features/matches/domain/entities/match_entity.dart';
import 'package:cricklo/features/matches/domain/entities/overall_score_entity.dart';
import 'package:cricklo/features/teams/domain/entities/player_entity.dart';
import 'package:cricklo/features/teams/domain/entities/team_entity.dart';
import 'package:cricklo/features/tournament/domain/entities/tournament_entity.dart';

final dummyCurrUser = UserEntity(
  userFollow: false,
  followers: 0,
  following: 0,
  profileId: "P009",
  phoneNumber: "6386291080",
  name: "Raghvedra Mishra",
  email: "raghvendramishra2002@gmail.com",
  location: LocationEntity(
    area: "Gomti Nagar",
    city: "Lucknow",
    state: "UP",
    lat: 0,
    lng: 0,
  ),
  playerType: PlayerType.allRounder,
  batterType: BatterType.leftHand,
  bowlerType: BowlerType.leftArmPace,
  unreadNotifications: 0,
  profilePic: '',
  userMatches: [],
  tournaments: [],
  matchwiseStats: [],
);

final PlayerEntity currUser = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.captain,
  id: 'siddhartha-0Z8jd97V1',
  playerId: 'siddhartha-0Z8jd97V1',
  name: 'Virat Kohli',
  captain: true,
  playerType: PlayerType.batter,
  batterType: BatterType.rightHand,
  bowlerType: null,
);

final PlayerEntity player1 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.captain,
  id: '3',
  playerId: 'P003',
  name: 'Virat Kohli',
  captain: true,
  playerType: PlayerType.batter,
  batterType: BatterType.rightHand,
  bowlerType: null,
);
final PlayerEntity player2 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.member,
  id: '4',
  playerId: 'P004',
  name: 'KL Rahul',
  captain: false,
  playerType: PlayerType.batter,
  batterType: BatterType.rightHand,
  bowlerType: null,
);
final PlayerEntity player3 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.invited,
  id: '5',
  playerId: 'P005',
  name: 'Rishabh Pant',
  captain: false,
  playerType: PlayerType.batter,
  batterType: BatterType.leftHand,
  bowlerType: null,
);
final PlayerEntity player4 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.invited,
  id: '6',
  playerId: 'P006',
  name: 'Hardik Pandya',
  captain: false,
  playerType: PlayerType.allRounder,
  batterType: BatterType.rightHand,
  bowlerType: BowlerType.rightArmPace,
);

final PlayerEntity player5 = PlayerEntity(
  profilePic: null,
  id: '1',
  teamRole: TeamRole.invited,
  playerId: 'P001',
  name: 'Rohit Sharma',
  captain: false,
  playerType: PlayerType.batter,
  batterType: BatterType.rightHand,
  bowlerType: null,
);
final PlayerEntity player6 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.invited,
  id: '2',
  playerId: 'P002',
  name: 'Shikhar Dhawan',
  captain: false,
  playerType: PlayerType.batter,
  batterType: BatterType.leftHand,
  bowlerType: null,
);
final PlayerEntity player7 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.invited,
  id: '7',
  playerId: 'P007',
  name: 'Ravindra Jadeja',
  captain: false,
  playerType: PlayerType.allRounder,
  batterType: BatterType.leftHand,
  bowlerType: BowlerType.leftArmSpin,
);
final PlayerEntity player8 = PlayerEntity(
  profilePic: null,
  teamRole: TeamRole.invited,
  id: '8',
  playerId: 'P008',
  name: 'Axar Patel',
  captain: false,
  playerType: PlayerType.allRounder,
  batterType: BatterType.leftHand,
  bowlerType: BowlerType.leftArmSpin,
);

final TeamEntity dummyTeam = TeamEntity(
  userFollows: false,
  followers: 0,
  uuid: "t002",
  inviteStatus: null,
  id: "t001",
  name: "Hello World",
  teamLogo: "assets/images/team_1.png",
  teamBanner: "",
  players: [player1, player2, player3, player4],
  location: LocationEntity(
    area: "Lakhimpur",
    city: "Lakhimpur",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  battingStats: [],
  bowlingStats: [],
  fieldingStats: [],
  matches: [],
  tournaments: [],
  partnershipStats: [],
  pointsStats: [],
);

final TeamEntity dummyTeam2 = TeamEntity(
  userFollows: false,
  followers: 0,
  uuid: "t002",
  inviteStatus: null,
  id: "t002",
  name: "Bye World",
  teamLogo: "assets/images/team_2.png",
  teamBanner: "",
  players: [player5, player6, player7, player8],
  location: LocationEntity(
    area: "Lakhimpur",
    city: "Lakhimpur",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  battingStats: [],
  bowlingStats: [],
  fieldingStats: [],
  matches: [],
  tournaments: [],
  partnershipStats: [],
  pointsStats: [],
);

final List<PlayerEntity> dummyPlayers = [
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '9',
    playerId: 'P009',
    name: 'Shreyas Iyer',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '10',
    playerId: 'P010',
    name: 'Suryakumar Yadav',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '11',
    playerId: 'P011',
    name: 'Jasprit Bumrah',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '12',
    playerId: 'P012',
    name: 'Mohammed Shami',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '13',
    playerId: 'P013',
    name: 'Bhuvneshwar Kumar',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '14',
    playerId: 'P014',
    name: 'Yuzvendra Chahal',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmSpin,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '15',
    playerId: 'P015',
    name: 'Kuldeep Yadav',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.leftArmSpin,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '16',
    playerId: 'P016',
    name: 'Washington Sundar',
    captain: false,
    playerType: PlayerType.allRounder,
    batterType: BatterType.leftHand,
    bowlerType: BowlerType.rightArmSpin,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '17',
    playerId: 'P017',
    name: 'Deepak Chahar',
    captain: false,
    playerType: PlayerType.bowler,
    batterType: null,
    bowlerType: BowlerType.rightArmPace,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '18',
    playerId: 'P018',
    name: 'Prithvi Shaw',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '19',
    playerId: 'P019',
    name: 'Mayank Agarwal',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
  PlayerEntity(
    profilePic: null,
    teamRole: TeamRole.invited,
    id: '20',
    playerId: 'P020',
    name: 'Sanju Samson',
    captain: false,
    playerType: PlayerType.batter,
    batterType: BatterType.rightHand,
    bowlerType: null,
  ),
];

final MatchEntity dummyMatchScheduled = MatchEntity(
  followCount: 0,
  follows: false,
  matchCategory: MatchCategory.open,
  tournamentName: '',
  matchStatus: MatchStatus.ongoing,
  matchID: "match-0001",
  dateAndTime: DateTime.now().add(Duration(days: 1)),
  overs: 20,
  matchType: MatchType.t20,
  teamA: dummyTeam,
  teamB: dummyTeam2,
  location: LocationEntity(
    location: "Ambedkar Park",
    area: "Vishwas Khand",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  scorer: {"profileId": currUser.playerId, "name": currUser.name},
);

final MatchEntity dummyMatchLive = MatchEntity(
  followCount: 0,
  follows: false,
  matchCategory: MatchCategory.open,
  tournamentName: '',
  matchStatus: MatchStatus.ongoing,
  matchID: "match-0001",
  dateAndTime: DateTime.now(),
  overs: 20,
  matchType: MatchType.t20,
  teamA: dummyTeam,
  teamB: dummyTeam2,
  location: LocationEntity(
    location: "Ambedkar Park",
    area: "Vishwas Khand",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  scorer: {"profileId": currUser.playerId, "name": currUser.name},
);

final MatchEntity dummyMatchTossDone = MatchEntity(
  followCount: 0,
  follows: false,
  matchCategory: MatchCategory.open,
  tournamentName: '',
  matchStatus: MatchStatus.ongoing,
  matchID: "match-0001",
  dateAndTime: DateTime.now(),
  overs: 20,
  matchType: MatchType.t20,
  teamA: dummyTeam,
  teamB: dummyTeam2,
  tossWinner: "t002",
  tossChoice: TossChoice.batting,
  teamBScore: OverallScoreEntity(
    team: dummyTeam,
    score: 0,
    overs: "0",
    wickets: 0,
  ),
  location: LocationEntity(
    location: "Ambedkar Park",
    area: "Vishwas Khand",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  scorer: {"profileId": currUser.playerId, "name": currUser.name},
);

final MatchEntity dummyMatchInningsTwo = MatchEntity(
  followCount: 0,
  follows: false,
  matchCategory: MatchCategory.open,
  tournamentName: '',
  matchStatus: MatchStatus.ongoing,
  matchID: "match-0001",
  dateAndTime: DateTime.now(),
  overs: 20,
  matchType: MatchType.t20,
  teamA: dummyTeam,
  teamB: dummyTeam2,
  tossWinner: "t001",
  tossChoice: TossChoice.batting,
  teamAScore: OverallScoreEntity(
    team: dummyTeam,
    score: 200,
    overs: "19.1",
    wickets: 10,
  ),
  teamBScore: OverallScoreEntity(
    team: dummyTeam2,
    score: 0,
    overs: "0",
    wickets: 0,
  ),
  location: LocationEntity(
    location: "Ambedkar Park",
    area: "Vishwas Khand",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  scorer: {"profileId": currUser.playerId, "name": currUser.name},
);

final MatchEntity dummyMatchDone = MatchEntity(
  followCount: 0,
  follows: false,
  matchCategory: MatchCategory.open,
  tournamentName: '',
  matchStatus: MatchStatus.ongoing,
  matchID: "match-0001",
  dateAndTime: DateTime.now(),
  overs: 20,
  matchType: MatchType.t20,
  teamA: dummyTeam,
  teamB: dummyTeam2,
  tossWinner: "t001",
  tossChoice: TossChoice.batting,
  teamAScore: OverallScoreEntity(
    team: dummyTeam,
    score: 200,
    overs: "19.1",
    wickets: 10,
  ),
  teamBScore: OverallScoreEntity(
    team: dummyTeam2,
    score: 120,
    overs: "18.3",
    wickets: 10,
  ),
  location: LocationEntity(
    location: "Ambedkar Park",
    area: "Vishwas Khand",
    city: "Lucknow",
    state: "Uttar Pradesh",
    lat: 0,
    lng: 0,
  ),
  winner: "t001",
  scorer: {"profileId": currUser.playerId, "name": currUser.name},
);

final tournament = TournamentEntity(
  userFollow: false,
  followers: 0,
  organizerId: "",
  id: "TOUR_001",
  name: "Punjab League",
  maxTeams: 12,
  spotsLeft: 12,
  banner: "",
  inviteDeadline: DateTime.now().add(Duration(days: 1)),
  startDate: DateTime.now().add(Duration(days: 2)),
  endDate: DateTime.now().add(Duration(days: 10)),
  matchType: MatchType.odi,
  tournamentType: TournamentType.league,
  overs: 50,
  moderators: [],
  venues: [
    LocationEntity(area: "Academy", city: "Bareilly", state: "Uttar Pradesh"),
  ],
  ballType: BallType.leather,
  teams: [],
  groupMatches: [],
  playoffMatches: [],
  groups: [],
  battingStats: [],
  bowlingStats: [],
  fieldingStats: [],
);
