final knockoutTest = {
  "success": true,
  "data": {
    "message": "Matches created successfully",
    "totalMatches": 6,
    "groupMatches": 2,
    "playoffMatches": 4,
    "groups": [
      {
        "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "matches": [
          {
            "matchId": "3a15173d-MG5JKM4ANT2",
            "dateAndTime": null,
            "overs": 0,
            "matchType": "TEST",
            "matchCategory": "GROUP",
            "status": "upcoming",
            "tossWinner": null,
            "tossChoice": null,
            "winner": null,
            "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
            "groupName": "Group A",
            "location": null,
            "teamAEntity": {
              "id": "a3963715-ef72-46f6-a5e2-42cb530efb17",
              "teamId": "teamA-574732",
              "name": "Test Team A",
              "logo": "logoA.png",
              "owner": "c94e8bd4-4b58-43be-a62c-0a2a9d20b145",
              "location": null,
            },
            "teamBEntity": {
              "id": "c6550539-2691-4df5-ab49-d9c78ba6eb1e",
              "teamId": "team-c-50973b60-4a3",
              "name": "Chennai Champions",
              "logo": "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
              "owner": "c997c0d8-b35c-431e-bf92-524d1bd24460",
              "location": null,
            },
            "scorerEntity": null,
            "follows": false,
          },
        ],
      },
      {
        "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "matches": [
          {
            "matchId": "3a15173d-YPAb4rgDdHY",
            "dateAndTime": null,
            "overs": 0,
            "matchType": "TEST",
            "matchCategory": "GROUP",
            "status": "upcoming",
            "tossWinner": null,
            "tossChoice": null,
            "winner": null,
            "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
            "groupName": "Group B",
            "location": null,
            "teamAEntity": {
              "id": "cc99c01c-e1c3-4459-89c2-4210cdaceb40",
              "teamId": "team-f-669de093-1b5",
              "name": "Mumbai Fighters",
              "logo": "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
              "owner": "8582ef10-b1fc-4009-a4ad-55502a77d7b4",
              "location": null,
            },
            "teamBEntity": {
              "id": "eecbd1b9-5fba-47bd-8341-0370d2994ece",
              "teamId": "team-e-19df90e5-8f2",
              "name": "Kolkata Eagles",
              "logo": "https://via.placeholder.com/200/8E44AD/FFFFFF?text=E",
              "owner": "dba17a73-0dda-488b-b88b-0564bd6dafc0",
              "location": null,
            },
            "scorerEntity": null,
            "follows": false,
          },
        ],
      },
    ],
    "playoffs": [
      {
        "matchId": "3a15173d-YPAb4rgDgCX",
        "dateAndTime": null,
        "overs": 0,
        "matchType": "TEST",
        "matchCategory": "QUALIFIER1",
        "status": "upcoming",
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "groupId": null,
        "groupName": null,
        "location": null,
        "teamAEntity": null,
        "teamBEntity": null,
        "scorerEntity": null,
        "follows": false,
      },
      {
        "matchId": "3a15173d-Rz91mPkqkS8",
        "dateAndTime": null,
        "overs": 0,
        "matchType": "TEST",
        "matchCategory": "ELIMINATOR",
        "status": "upcoming",
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "groupId": null,
        "groupName": null,
        "location": null,
        "teamAEntity": null,
        "teamBEntity": null,
        "scorerEntity": null,
        "follows": false,
      },
      {
        "matchId": "3a15173d-mBMoKjEOEFK",
        "dateAndTime": null,
        "overs": 0,
        "matchType": "TEST",
        "matchCategory": "QUALIFIER2",
        "status": "upcoming",
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "groupId": null,
        "groupName": null,
        "location": null,
        "teamAEntity": null,
        "teamBEntity": null,
        "scorerEntity": null,
        "follows": false,
      },
      {
        "matchId": "3a15173d-bLGA5NDrDuo",
        "dateAndTime": null,
        "overs": 0,
        "matchType": "TEST",
        "matchCategory": "FINAL",
        "status": "upcoming",
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "groupId": null,
        "groupName": null,
        "location": null,
        "teamAEntity": null,
        "teamBEntity": null,
        "scorerEntity": null,
        "follows": false,
      },
    ],
  },
};
