final test = {
  "success": true,
  "errorCode": null,
  "errorMessage": null,
  "payload": {
    "tournamentId": "tour-GW-Gm6n2Rqn",
    "tournamentName": "Gujarat Warriors",
    "banner":
        "https://bxgiwtigvagzyllsmxif.supabase.co/storage/v1/object/public/cricklo-user-assets/tournaments/Gujarat%20Warriors/banner.octet-stream",
    "format": "TEST",
    "tournamentType": "KNOCKOUT",
    "overs": 0,
    "ballType": "LEATHER",
    "startDate": "2025-10-29T00:00:00.000Z",
    "endDate": "2025-10-31T00:00:00.000Z",
    "inviteDeadline": "2025-10-29T00:00:00.000Z",
    "numberOfTeams": 12,
    "createdAt": "2025-10-27T18:39:04.000Z",
    "followersCount": 1,
    "followingCount": 0,
    "follows": true,
    "organizer": {
      "profileId": "user1-704563",
      "userId": "51c5383e-9530-46e6-8a78-90bd9c40ae46",
      "name": "User 1",
      "email": "user1@example.com",
      "phoneNumber": "9000000001",
      "profilePicture": null,
    },
    "moderators": [
      {
        "profileId": "user10-487760",
        "userId": "09b704ee-0530-426d-9d2a-a5bdff2e4426",
        "name": "User 10",
        "email": "user10@example.com",
        "phoneNumber": "90000000010",
        "profilePicture": null,
        "moderatorId": null,
        "status": "PENDING",
        "inviteId": "e611c62c-5310-4d49-8b6b-f16cab932b09",
        "invitedAt": "2025-10-27T18:39:05.070Z",
      },
    ],
    "teams": [
      {
        "teamId": "teamA-574732",
        "teamName": "Test Team A",
        "teamLogo": "logoA.png",
        "teamBanner": "bannerA.png",
        "inviteStatus": "ACCEPTED",
        "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
      {
        "teamId": "teamB-642392",
        "teamName": "Test Team B",
        "teamLogo": "logoB.png",
        "teamBanner": "bannerB.png",
        "inviteStatus": "ACCEPTED",
        "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
      {
        "teamId": "team-c-50973b60-4a3",
        "teamName": "Chennai Champions",
        "teamLogo": "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
        "teamBanner":
            "https://via.placeholder.com/1200x400/FF6B35/FFFFFF?text=Chennai+Champions",
        "inviteStatus": "ACCEPTED",
        "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
      {
        "teamId": "team-e-19df90e5-8f2",
        "teamName": "Kolkata Eagles",
        "teamLogo": "https://via.placeholder.com/200/8E44AD/FFFFFF?text=E",
        "teamBanner":
            "https://via.placeholder.com/1200x400/8E44AD/FFFFFF?text=Kolkata+Eagles",
        "inviteStatus": "ACCEPTED",
        "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
      {
        "teamId": "team-f-669de093-1b5",
        "teamName": "Mumbai Fighters",
        "teamLogo": "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
        "teamBanner":
            "https://via.placeholder.com/1200x400/27AE60/FFFFFF?text=Mumbai+Fighters",
        "inviteStatus": "ACCEPTED",
        "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
      {
        "teamId": "team-d-b0fb4a18-46a",
        "teamName": "Delhi Daredevils",
        "teamLogo": "https://via.placeholder.com/200/004E89/FFFFFF?text=D",
        "teamBanner":
            "https://via.placeholder.com/1200x400/004E89/FFFFFF?text=Delhi+Daredevils",
        "inviteStatus": "ACCEPTED",
        "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "location": {
          "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
          "venue": null,
          "area": "Sector 18",
          "city": "Noida",
          "state": "UP",
          "coordinates": "28.5700,77.3200",
        },
      },
    ],
    "venues": [
      {
        "id": "c9a1bfd7-923d-403a-a4aa-35cf842cebb3",
        "venue": null,
        "area": "Area",
        "city": "City",
        "state": "State",
        "coordinates": null,
      },
    ],
    "groups": [
      {
        "id": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "teams": [
          {
            "teamId": "teamA-574732",
            "teamName": "Test Team A",
            "teamLogo": "logoA.png",
            "teamBanner": "bannerA.png",
            "inviteStatus": "ACCEPTED",
            "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
            "groupName": "Group A",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
          {
            "teamId": "teamB-642392",
            "teamName": "Test Team B",
            "teamLogo": "logoB.png",
            "teamBanner": "bannerB.png",
            "inviteStatus": "ACCEPTED",
            "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
            "groupName": "Group A",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
          {
            "teamId": "team-c-50973b60-4a3",
            "teamName": "Chennai Champions",
            "teamLogo": "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
            "teamBanner":
                "https://via.placeholder.com/1200x400/FF6B35/FFFFFF?text=Chennai+Champions",
            "inviteStatus": "ACCEPTED",
            "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
            "groupName": "Group A",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
        ],
      },
      {
        "id": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "teams": [
          {
            "teamId": "team-e-19df90e5-8f2",
            "teamName": "Kolkata Eagles",
            "teamLogo": "https://via.placeholder.com/200/8E44AD/FFFFFF?text=E",
            "teamBanner":
                "https://via.placeholder.com/1200x400/8E44AD/FFFFFF?text=Kolkata+Eagles",
            "inviteStatus": "ACCEPTED",
            "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
            "groupName": "Group B",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
          {
            "teamId": "team-f-669de093-1b5",
            "teamName": "Mumbai Fighters",
            "teamLogo": "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
            "teamBanner":
                "https://via.placeholder.com/1200x400/27AE60/FFFFFF?text=Mumbai+Fighters",
            "inviteStatus": "ACCEPTED",
            "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
            "groupName": "Group B",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
          {
            "teamId": "team-d-b0fb4a18-46a",
            "teamName": "Delhi Daredevils",
            "teamLogo": "https://via.placeholder.com/200/004E89/FFFFFF?text=D",
            "teamBanner":
                "https://via.placeholder.com/1200x400/004E89/FFFFFF?text=Delhi+Daredevils",
            "inviteStatus": "ACCEPTED",
            "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
            "groupName": "Group B",
            "location": {
              "id": "7ff75fbc-94c4-4c06-b1d6-50218520f23f",
              "venue": null,
              "area": "Sector 18",
              "city": "Noida",
              "state": "UP",
              "coordinates": "28.5700,77.3200",
            },
          },
        ],
      },
    ],
    "ungroupedTeams": null,
    "matchesByGroup": [
      {
        "id": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
        "groupName": "Group A",
        "matches": [
          {
            "matchId": "3a15173d-MG5JKM4ANT2",
            "date": "2025-10-28T00:00:00.000Z",
            "time": "1970-01-01T23:04:00.000Z",
            "dateAndTime": "2025-10-28T23:04:00.000Z",
            "format": "TEST",
            "overs": 0,
            "ballType": "LEATHER",
            "matchType": "TEST",
            "matchCategory": "GROUP",
            "status": "upcoming",
            "teamAEntity": {
              "teamId": "teamA-574732",
              "teamName": "Test Team A",
              "teamLogo": "logoA.png",
            },
            "teamBEntity": {
              "teamId": "team-c-50973b60-4a3",
              "teamName": "Chennai Champions",
              "teamLogo":
                  "https://via.placeholder.com/200/FF6B35/FFFFFF?text=C",
            },
            "location": {
              "area": "Area",
              "city": "City",
              "state": "State",
              "coordinates": null,
            },
            "scorerEntity": {
              "profileId": "user1-704563",
              "name": "User 1",
              "profilePhoto": null,
              "inviteStatus": "ACCEPTED",
            },
            "groupId": "2fa0c0da-dd04-426c-a82e-3199da6123b7",
            "groupName": "Group A",
            "tossWinner": null,
            "tossChoice": null,
            "winner": null,
            "targetChanged": false,
            "teamAScore": 0,
            "teamAWicketsLost": 0,
            "teamBScore": 0,
            "teamBWicketsLost": 0,
          },
        ],
      },
      {
        "id": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
        "groupName": "Group B",
        "matches": [
          {
            "matchId": "3a15173d-YPAb4rgDdHY",
            "date": null,
            "time": null,
            "dateAndTime": null,
            "format": "TEST",
            "overs": 0,
            "ballType": "LEATHER",
            "matchType": "TEST",
            "matchCategory": "GROUP",
            "status": "upcoming",
            "teamAEntity": {
              "teamId": "team-f-669de093-1b5",
              "teamName": "Mumbai Fighters",
              "teamLogo":
                  "https://via.placeholder.com/200/27AE60/FFFFFF?text=F",
            },
            "teamBEntity": {
              "teamId": "team-e-19df90e5-8f2",
              "teamName": "Kolkata Eagles",
              "teamLogo":
                  "https://via.placeholder.com/200/8E44AD/FFFFFF?text=E",
            },
            "location": null,
            "scorerEntity": null,
            "groupId": "53745e32-acf4-4ef5-a05a-e4b212d3b4d7",
            "groupName": "Group B",
            "tossWinner": null,
            "tossChoice": null,
            "winner": null,
            "targetChanged": false,
            "teamAScore": 0,
            "teamAWicketsLost": 0,
            "teamBScore": 0,
            "teamBWicketsLost": 0,
          },
        ],
      },
    ],
    "ungroupedMatches": [
      {
        "matchId": "3a15173d-YPAb4rgDgCX",
        "date": null,
        "time": null,
        "dateAndTime": null,
        "format": "TEST",
        "overs": 0,
        "ballType": "LEATHER",
        "matchType": "TEST",
        "matchCategory": "QUALIFIER1",
        "status": "upcoming",
        "teamAEntity": null,
        "teamBEntity": null,
        "location": null,
        "scorerEntity": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "targetChanged": false,
        "teamAScore": 0,
        "teamAWicketsLost": 0,
        "teamBScore": 0,
        "teamBWicketsLost": 0,
      },
      {
        "matchId": "3a15173d-Rz91mPkqkS8",
        "date": null,
        "time": null,
        "dateAndTime": null,
        "format": "TEST",
        "overs": 0,
        "ballType": "LEATHER",
        "matchType": "TEST",
        "matchCategory": "ELIMINATOR",
        "status": "upcoming",
        "teamAEntity": null,
        "teamBEntity": null,
        "location": null,
        "scorerEntity": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "targetChanged": false,
        "teamAScore": 0,
        "teamAWicketsLost": 0,
        "teamBScore": 0,
        "teamBWicketsLost": 0,
      },
      {
        "matchId": "3a15173d-mBMoKjEOEFK",
        "date": null,
        "time": null,
        "dateAndTime": null,
        "format": "TEST",
        "overs": 0,
        "ballType": "LEATHER",
        "matchType": "TEST",
        "matchCategory": "QUALIFIER2",
        "status": "upcoming",
        "teamAEntity": null,
        "teamBEntity": null,
        "location": null,
        "scorerEntity": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "targetChanged": false,
        "teamAScore": 0,
        "teamAWicketsLost": 0,
        "teamBScore": 0,
        "teamBWicketsLost": 0,
      },
      {
        "matchId": "3a15173d-bLGA5NDrDuo",
        "date": null,
        "time": null,
        "dateAndTime": null,
        "format": "TEST",
        "overs": 0,
        "ballType": "LEATHER",
        "matchType": "TEST",
        "matchCategory": "FINAL",
        "status": "upcoming",
        "teamAEntity": null,
        "teamBEntity": null,
        "location": null,
        "scorerEntity": null,
        "groupId": null,
        "groupName": null,
        "tossWinner": null,
        "tossChoice": null,
        "winner": null,
        "targetChanged": false,
        "teamAScore": 0,
        "teamAWicketsLost": 0,
        "teamBScore": 0,
        "teamBWicketsLost": 0,
      },
    ],
    "totalTeams": 6,
    "totalAcceptedTeams": 6,
    "totalMatches": 6,
    "totalVenues": 1,
  },
};
